---
function:
  name: dell-narvar-pod-doc-shipment-file-stream-processor-${self:provider.stage}
  handler: src/dell-narvar-pod-doc/shipment-file-stream-processor.handler
  memorySize: 2048
  timeout: 900
  layers:
    - !Ref NodeModulesLambdaLayer
  package:
    patterns:
      - '!**/*'
      - src/dell-narvar-pod-doc/shipment-file-stream-processor.js
      - src/dell-narvar-pod-doc/helper.js

  events:
    - stream:
        arn: ${ssm:/omni-wt-rt/${self:provider.stage}/shipment-file/stream-arn}
        batchSize: 5
        maximumRetryAttempts: 3
        bisectBatchOnFunctionError: true
        filterPatterns:
          - { dynamodb: { NewImage: { CustomerAccess: { S: ['Y'] } } } }
