---
function:
  name: dell-narvar-das-event-processor-${self:provider.stage}
  handler: src/dell-narvar-eventing/das-event-processor.handler
  tags:
    Name: das-event-processor
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 900

  package:
    patterns:
      - '!**/*'
      - src/dell-narvar-eventing/das-event-processor.js

  layers:
    - !Ref NodeModulesLambdaLayer

  events:
    - stream:
        arn: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipper/ddb.streamArn}
        batchSize: 5
        maximumRetryAttempts: 3
        bisectBatchOnFunctionError: true

    - stream:
        arn: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/consignee/ddb.streamArn}
        batchSize: 5
        maximumRetryAttempts: 3
        bisectBatchOnFunctionError: true

    - stream:
        arn: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.streamArn}
        batchSize: 5
        maximumRetryAttempts: 3
        bisectBatchOnFunctionError: true

    - stream:
        arn: ${ssm:/dell-narvar-eventing/${self:provider.stage}/status/ddb.arn}
        batchSize: 5
        maximumRetryAttempts: 3
        bisectBatchOnFunctionError: true
        filterPatterns:
          - { dynamodb: { NewImage: { Status: { S: ['READY'] } } } }

  environment:
    STAGE: ${self:provider.stage}
    SHIPMENT_HEADER_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.tableName}
    CONSIGNEE_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/consignee/ddb.tableName}
    SHIPPER_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipper/ddb.tableName}
    EVENTING_TOPICS_TABLE: ${ssm:/omni/${self:provider.stage}/eventing/topics/table/name}
    ERROR_SNS_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
    CUSTOMER_PREFERENCE_TABLE: ${ssm:/omni/${self:provider.stage}/eventing/preferences/table/name}
    CUSTOMER_ENTITLEMENT_TABLE: ${ssm:/omni-dw/${self:provider.stage}/customerEntitlement/table}
    ENTITLEMENT_HOUSEBILL_INDEX: ${ssm:/omni-dw/${self:provider.stage}/entitlement/HouseBillNumber/index}
    SHIPMENT_EVENT_STATUS_TABLE: ${ssm:/omni/${self:provider.stage}/eventing/event-status/table/name}
    STATUS_TABLE: ${ssm:/dell-narvar-eventing/${self:provider.stage}/status-table/name}
